# -*- coding: utf-8 -*-
"""python_tuple.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/Adsulanuradha/baccb7fdd0d95ff104583d98db948575/python_list.ipynb
"""

#Data Structure :1 TUPLE
#Lists are immutable
#created using square Brackets()
t1=(1,2,3,4,5)
t1

type(t1)

t1[2]

t1[0]=7  #will raise an error as tuples are immutable

t3=t1+(6,7,8,9,10)  #tuple to tuple add but we can notreplce the item
t3

dir(tuple)

t1.count(2)  ##in bracket we have passed an element not index they count

t1.index(4)

t2=(1,1,1,1,3,3,4,4,5)
t2.count(1)

#indexing and slicing with tuple is same as list
#extracting elements of tuple
t1[1:5]

t1[3:]



