# -*- coding: utf-8 -*-
"""python_introduction.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/Adsulanuradha/5342c7e47c4a08743892cf1e270c8597/python_introduction.ipynb
"""

city="anuradha"
city.count("a")
"anuradha".count("a")

name="anuradha"
name*4  #4 times anuradha is printed

n1=5
n1*3

name="anuradha"
surname="adsul"
name +" "+ surname  #concatenate without space

##Conditional Statement

a=130
b=50
if a>b:
  print("a is greater")
  print("In True block")
  c=a+b
  print(c)
else:
  print("b is greater than a")
  print("In false block")
  c=a*b
  print(c)

a=200
b=300

if (a>b):
  print(a,"greater number")
else:
  print("greater number:",b)  
  c=b-a
  print(c)

salary=25000
if(salary>20000):
  tax=0.25
  print("Hello from true if")
else:
  tax=0.20
  print("Hello from false if/else")
print("bye...outside of if block")
net_sal=salary-tax*salary
print("Net Salary=",net_sal)

#for loop  #assign 1 st limit to "i"#check whether i is less than last limit if yes then it will enter in the body of for loop if it is not then it goes to last statement
for i in range(5,10):#print numbers from 5 to 9 default increment is 1
    print(i)
print("bye")

for i in range(1,11,2):
  print(i)

#print a all odd numbers from 1 to 20
for i in range(1,20,2):
  print(i)
#print all even numbers from 1 to 20
for i in range(0,21,2):
  print(i)

#break statement terminates the loop when condition is statisfied 
for i in range(1,11):
  if i==5:
    print("same")
    break
  else:
    print(i)

for num in range(11):  #range is 0 to 10
  print(num,num*num,num**3) #num and its square and cube

#range (start ,stop,step)
for i in range(1,30,5):
  print(i,"@")

subject="Science"
for i in subject:
  print(i)

#print name 3 times on 1 st line 4 times on, 2nd line 5 time ,on 3rd,6 time ,on 4th time
name="Anuradha"
for i in range(3,7):
  print(name*i)

#print each letter of movie on separate line
#change case of each letter (upper to smaller smaller to upper)
movie="Drishyam"
for i in movie:
  #print(i)
  #print(i.swapcase)
  print(i.swapcase(),end=" ")

#print all even and odd numbers between given range using for loop
print("even number:")
for i in range(1,11):
  if i %2==0:
     print(i) 
print("odd number:")
for i in range(1,11):
  if i %2!=0:
    print(i)

status1=True
type(status1)
status2=False
type(status2)

#print each letter 4 times with separator
for i in "Data Science":
  print(i*4,end=" ")

len("Anu radha")

x="Data Science "
print(x*3,end=" ")

#Data structure: 1 LIST
#Lists are mutable
#created using square Brackets[]
marks=[40,55,70,60,80,85,78]
marks

type(marks)

dir(list)

len(marks)  #length of elements

new_marks=sorted(marks) #original list remains unchaned by using sorted function
new_marks

marks.sort()  #original list is sorted  in ascending order
marks

marks.append(35)   #add a function in the last of list
marks

marks.reverse()
marks

marks2=[40,48,59,60,89,30]
marks2.sort(reverse=True) ##sorts in descending order
marks2

marks3=[40,45,60,89,30]
marks3.sort() #by deafult list will sort it in ascending order
marks3

# if i want to check any element present in the list or not 
90 in marks

list1=[10,20,30]
list2=[70,40,50]
list1+list2  #concantenation of two elements

(list1+list2)*3 #multiplied 3 means list element repeat 3 times

#list of string
list3=["Mango","Apple","Banana","Pineapple","Custard apple","Straberry"]
list3

#display fruits by changing case of all fruits to uppercase
for fruits in list3:
# print(fruits.upper())
 # print(fruits.upper,end=" ")
  print(fruits.replace("u","a"),end=" ")

list3[5] ##indexing

list3.count("Apple")    #no times element is repeted

#slicing
list3[0:4] #it gives 0,1,2,3 indexing elements from the list

list3[1:] #one to last element

#from beginning to pineapple
list3[:4]

list3

#negative indexing
list3[-1]

list3[-3]

print(list3)
list3[::2]  ##start element,last element,step element 0to6 with difference 2

n1=list(range(1,31))
print(n1,end=" ")

n1[::4]

#print number from index 2 to 26 with step value of 5
n1[2:26:5]  #whatever we write in list that show the index number not element

print(list3,end=" ")

list3[::-2]

"the" in "netherland"

list4=['Mango','Apple','Banana','Pineapple','Custard Apple','Strawberry']
list4.append("Mulberry")

list4

list4.remove("Custard Apple")

list4

#display fruits which contain string as 'berry' using for loop
for fruits in list4:
  if 'berry' in fruits:
    print(fruits)

#disple the fruit which contain as 'pple' using for loop
for fruits in list4:
  if 'pple' in fruits:
    print(fruits)

list4.append("Black berry")

list4

#create list 6 from list 5 having only berry as substring and store remain in other list
list5=["mango","Apple","Banana","Pineapple","strwberry","Mulberry","black berry"]
list6=[]
list7=[]
list8=[]
for fruit in list5:
  if "berry" in fruit:
    list6.append(fruit)
  elif "pple" in fruit:
      list7.append(fruit)
  else:
    list8.append(fruit)
print(list6,end=" ")
print(list7,end=" ")
print(list8,end=" ")

#print squares of all numbers of list1 to list2
l1=[2,3,4,5,6]
l2=[]
for i in l1:
  l2.append(i**2)
print(l2,end=" ")

#List comprenhention -makes your code compact
l1=[2,3,4,5,6]
l2=[i**2 for i in l1]
print(l1,end=" ")
print(l2,end=" ")

list5

newlist=[fruit for fruit in list5 if 'berry' in fruit]
print(newlist,end=" ")

city=["kolhapur","solapur","Mumbai","satara"]
newlist=[i for i in city if "pur" in i]
print(newlist,end=" ")

list5.index("Apple")

#index 2 item was Banana which is replaced by orange
#list are mutable - you can replace items of list
list5[2]="Orange"
print(list5,end=" ")