# -*- coding: utf-8 -*-
"""Python_Dictionary.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ir4kgSgAe2VK187RmTrwnGBsyJIvSq8F
"""

#Data Structure: 3 DICTIONARY
#Dictionaries are used to store data values in "Key:value" pair
#a dictionary is a collection which is ordered,changeable and do not allow duplicate
#dictionaries are written with curly brackets{"key":"value"}and have keys and
#here ,keys are unique identifiers that are asscited with each value:
cp={"Nepal":"Kathmandu","Italy":"Rome","India":"Delhi"}
print(cp)

type(cp)

dir(dict)

#acess element of dictionary
cp["India"]

#keys()method extracts the keys of the dictionary and returns the list of keys as a view ob
keys=cp.keys()
keys

cp.values()

#the items() method returns a view object that displyas a list of dictionary's(key,value)
items=cp.items()
items

#the update() method the dictionary with the elements fromanother dictionary object
add_cp={"England":"London"}
cp.update(add_cp)
add_cp

cp

cp.update({"XYZ":"ABC"})
cp

cp["ABC"]=("Pune") #to change the value
cp

cp["ABC"]=("CDE")
cp

cp.popitem()   #last in first out
cp

cp

##Values can be of different data type
mylist=["Mango","Orange","Strawberry","Banana","Mulberry","Blackberry"]

mytuple=(20,30,40,50,60,70,90)

mydict={"A":mylist,
        "B":mytuple,
        "C":cp}
mydict

